sudo: false

matrix:
  include:
    - env: TOXENV=docs
    - env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35

install:
  - pip install -r requirements.txt

script:
  - make

